// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SnapManager.Data;

#nullable disable

namespace SnapManager.Data.DesignTime.Migrations.NpgsqlServer
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250628084616_NewScheme")]
    partial class NewScheme
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SnapManager.Models.Hierarchy.TreeItemBase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("TreeItems");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("TreeItemBaseTreeItemBase", b =>
                {
                    b.Property<int>("ChildrenId")
                        .HasColumnType("integer");

                    b.Property<int>("ParentsId")
                        .HasColumnType("integer");

                    b.HasKey("ChildrenId", "ParentsId");

                    b.HasIndex("ParentsId");

                    b.ToTable("TreeItemBaseTreeItemBase");
                });

            modelBuilder.Entity("SnapManager.Models.Credential", b =>
                {
                    b.HasBaseType("SnapManager.Models.Hierarchy.TreeItemBase");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<DateTime>("ModificationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.ToTable("Credentials");
                });

            modelBuilder.Entity("SnapManager.Models.Folder", b =>
                {
                    b.HasBaseType("SnapManager.Models.Hierarchy.TreeItemBase");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<DateTime>("ModificationDate")
                        .HasColumnType("timestamp with time zone");

                    b.ToTable("Folders");
                });

            modelBuilder.Entity("SnapManager.Models.FolderWithCredentials", b =>
                {
                    b.HasBaseType("SnapManager.Models.Folder");

                    b.ToTable("FoldersWithCredentials");
                });

            modelBuilder.Entity("TreeItemBaseTreeItemBase", b =>
                {
                    b.HasOne("SnapManager.Models.Hierarchy.TreeItemBase", null)
                        .WithMany()
                        .HasForeignKey("ChildrenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SnapManager.Models.Hierarchy.TreeItemBase", null)
                        .WithMany()
                        .HasForeignKey("ParentsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SnapManager.Models.Credential", b =>
                {
                    b.HasOne("SnapManager.Models.Hierarchy.TreeItemBase", null)
                        .WithOne()
                        .HasForeignKey("SnapManager.Models.Credential", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SnapManager.Models.Folder", b =>
                {
                    b.HasOne("SnapManager.Models.Hierarchy.TreeItemBase", null)
                        .WithOne()
                        .HasForeignKey("SnapManager.Models.Folder", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SnapManager.Models.FolderWithCredentials", b =>
                {
                    b.HasOne("SnapManager.Models.Folder", null)
                        .WithOne()
                        .HasForeignKey("SnapManager.Models.FolderWithCredentials", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
