// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SnapManager.Data;

#nullable disable

namespace SnapManager.Data.DesignTime.Migrations.NpgsqlServer
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250723135755_SepModels")]
    partial class SepModels
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SnapManager.Models.DomainModels.TreeItemDModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ParentId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("hierarchy_scheme");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("SnapManager.Models.DomainModels.CredentialDModel", b =>
                {
                    b.HasBaseType("SnapManager.Models.DomainModels.TreeItemDModel");

                    b.Property<DateTime>("CreationDateUTC")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<DateTime>("ModificationDateUTC")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.ToTable("credentials");
                });

            modelBuilder.Entity("SnapManager.Models.DomainModels.FolderDModel", b =>
                {
                    b.HasBaseType("SnapManager.Models.DomainModels.TreeItemDModel");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<DateTime>("ModificationDate")
                        .HasColumnType("timestamp with time zone");

                    b.ToTable("folders");
                });

            modelBuilder.Entity("SnapManager.Models.DomainModels.FolderWithCredentialsDModel", b =>
                {
                    b.HasBaseType("SnapManager.Models.DomainModels.FolderDModel");

                    b.ToTable("folders_with_credentials");
                });

            modelBuilder.Entity("SnapManager.Models.DomainModels.TreeItemDModel", b =>
                {
                    b.HasOne("SnapManager.Models.DomainModels.TreeItemDModel", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("SnapManager.Models.DomainModels.CredentialDModel", b =>
                {
                    b.HasOne("SnapManager.Models.DomainModels.TreeItemDModel", null)
                        .WithOne()
                        .HasForeignKey("SnapManager.Models.DomainModels.CredentialDModel", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SnapManager.Models.DomainModels.FolderDModel", b =>
                {
                    b.HasOne("SnapManager.Models.DomainModels.TreeItemDModel", null)
                        .WithOne()
                        .HasForeignKey("SnapManager.Models.DomainModels.FolderDModel", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SnapManager.Models.DomainModels.FolderWithCredentialsDModel", b =>
                {
                    b.HasOne("SnapManager.Models.DomainModels.FolderDModel", null)
                        .WithOne()
                        .HasForeignKey("SnapManager.Models.DomainModels.FolderWithCredentialsDModel", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SnapManager.Models.DomainModels.TreeItemDModel", b =>
                {
                    b.Navigation("Children");
                });
#pragma warning restore 612, 618
        }
    }
}
